version: "3"
services:
  fuzz-ffmpeg:
    build: ffmpeg
    restart: always
    volumes:
      - ./ffmpeg_input:/root/ffmpeg_input
      - ./ffmpeg_output:/root/ffmpeg_output
      - ./ffmpeg_sources:/root/ffmpeg_sources
      - ./ffmpeg_bin:/root/bin
