version: "3"
services:
  fuzz-ffmpeg:
    build: ffmpeg
    restart: always
    volumes:
      - ./ffmpeg_input:/ffmpeg_input
      - ./ffmpeg_output:/ffmpeg_output
      - ./ffmpeg_afl_scripts:/ffmpeg_afl_scripts
